In [130]:
import json
import numpy as np 
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.svm import SVC
import csv

#un-comment line below to print whole numpy arrays (note that computing cost will be much higher)
np.set_printoptions(threshold=np.nan)

#this opens_loads the json files and assign them to their corresponding variables

dict_bright = json.load(open("bright_analysis.json", 'rb'))
dict_metal = json.load(open("metal_analysis.json",'rb'))
dict_hard = json.load(open("hard_analysis.json",'rb'))
dict_reverb = json.load(open("reverb_analysis.json",'rb'))
dict_rough = json.load(open("rough_analysis.json",'rb'))


In [131]:
#importing CSV files 

with open('bright.csv', 'rb') as f:
    reader = csv.reader(f)
    bright_list_csv = list(reader)
    #removing brackets from list
    bright_list = [l[0] for l in bright_list_csv]
    
with open('warm.csv', 'rb') as f:
    reader = csv.reader(f)
    warm_list_csv = list(reader)
    warm_list = [l[0] for l in warm_list_csv]
    
with open('rough.csv', 'rb') as f:
    reader = csv.reader(f)
    rough_list_csv = map(tuple, reader)
    rough_list = [l[0] for l in rough_list_csv]
    
with open('reverb.csv', 'rb') as f:
    reader = csv.reader(f)
    reverb_list_csv = map(tuple, reader)
    reverb_list = [l[0] for l in reverb_list_csv]
    
with open('clear.csv', 'rb') as f:
    reader = csv.reader(f)
    clear_list_csv = list(reader)
    clear_list = [l[0] for l in clear_list_csv]
    
with open('hollow.csv', 'rb') as f:
    reader = csv.reader(f)
    hollow_list_csv = list(reader)
    hollow_list = [l[0] for l in hollow_list_csv]
    
with open('deep.csv', 'rb') as f:
    reader = csv.reader(f)
    deep_list_csv = list(reader)
    deep_list = [l[0] for l in deep_list_csv]
    
with open('punchy.csv', 'rb') as f:
    reader = csv.reader(f)
    punchy_list_csv = list(reader)
    punchy_list = [l[0] for l in punchy_list_csv]
    
with open('metallic.csv', 'rb') as f:
    reader = csv.reader(f)
    metallic_list_csv = list(reader)
    metallic_list = [l[0] for l in metallic_list_csv]
    
with open('sharp.csv', 'rb') as f:
    reader = csv.reader(f)
    sharp_list_csv = list(reader)
    sharp_list = [l[0] for l in sharp_list_csv]
    
with open('hard.csv', 'rb') as f:
    reader = csv.reader(f)
    hard_list_csv = list(reader) 
    hard_list = [l[0] for l in hard_list_csv]



In [132]:
#hard_list #print if want to see content.change accordingly for other lists

In [133]:
len(hard_list)

502

In [134]:
#El número de sonidos en tu dataset:
nb_sounds = len(set(bright_list + hard_list +warm_list + rough_list + reverb_list + clear_list + hollow_list + deep_list + punchy_list + metallic_list + sharp_list))



In [135]:
sounds_list = (set(bright_list + hard_list +warm_list + rough_list + reverb_list + clear_list + hollow_list + deep_list + punchy_list + metallic_list + sharp_list))

In [136]:
with open("sounds_list.txt", "w") as output:
    output.write(str(sounds_list))

#Showing VALUES == 'nan' to be removed later on. 
for keys, values in dict_bright.iteritems():
    print("BRIGHT-FreesoundID: %s VALUE: %s" % (keys, values))
    if dict_bright[keys] == 'nan':
        dict_bright.iteritems
    
for keys, values in dict_metal.iteritems():
    print("METAL-FreesoundID: %s VALUE: %s" % (keys, values))

for keys, values in dict_hard.iteritems():
    print("HARD VALUES-FreesoundID: %s VALUE: %s" % (keys, values))
    
    
for keys, values in dict_reverb.iteritems():
    print("REVERB VALUES-FreesoundID:%s VALUE: %s" % (keys, values))
    
for keys, values in dict_rough.iteritems():
    print("ROUGH VALUES-FreesoundID: %s VALUE: %s" % (keys, values))


In [137]:
print "bright length:",len(dict_bright)
print "metal length:",len(dict_metal)
print "hard length:",len(dict_hard)
print "reverb length:",len(dict_reverb)
print "rough length:",len(dict_rough)

bright length: 2745
metal length: 2645
hard length: 2735
reverb length: 2422
rough length: 2736


In [138]:
#Cleaning_removing "nan" values from the dicts
clean_dict_bright = filter(lambda k: not np.isnan(dict_bright[k]), dict_bright)
clean_dict_metal = filter(lambda k: not np.isnan(dict_metal[k]), dict_metal)
clean_dict_hard = filter(lambda k: not np.isnan(dict_hard[k]), dict_hard)
clean_dict_reverb = filter(lambda k: not np.isnan(dict_reverb[k]), dict_reverb)
clean_dict_rough = filter(lambda k: not np.isnan(dict_rough[k]), dict_rough)

In [139]:
print "bright length:",len(clean_dict_bright)
print "metal length:",len(clean_dict_metal)
print "hard length:",len(clean_dict_hard)
print "reverb length:",len(clean_dict_reverb)
print "rough length:",len(clean_dict_rough)

bright length: 2745
metal length: 2562
hard length: 2721
reverb length: 2422
rough length: 2736


In [140]:
#clean_dict_bright #checking out one of them to see content

[u'127150',
 u'110554',
 u'110550',
 u'36097',
 u'370250',
 u'370925',
 u'77164',
 u'78856',
 u'135770',
 u'73087',
 u'110481',
 u'73085',
 u'73084',
 u'73083',
 u'131599',
 u'120438',
 u'73264',
 u'74835',
 u'94205',
 u'120432',
 u'120433',
 u'120430',
 u'120436',
 u'261857',
 u'120434',
 u'120435',
 u'189575',
 u'257233',
 u'139555',
 u'101161',
 u'354182',
 u'135036',
 u'131202',
 u'25666',
 u'87586',
 u'100706',
 u'266919',
 u'376950',
 u'104662',
 u'335962',
 u'392119',
 u'13540',
 u'219945',
 u'219944',
 u'219943',
 u'186917',
 u'117096',
 u'166732',
 u'131118',
 u'8208',
 u'117091',
 u'353405',
 u'90535',
 u'117098',
 u'117099',
 u'220237',
 u'220545',
 u'96136',
 u'234587',
 u'2442',
 u'46262',
 u'221961',
 u'122619',
 u'235968',
 u'42902',
 u'235960',
 u'377772',
 u'361490',
 u'90790',
 u'173544',
 u'191515',
 u'269541',
 u'351823',
 u'351822',
 u'192556',
 u'192557',
 u'351827',
 u'351824',
 u'212821',
 u'173838',
 u'345083',
 u'94027',
 u'46646',
 u'141121',
 u'302369',
 u'3

In [141]:
#applying intersection to all the lists
all_ids_intersection=list(set(clean_dict_bright) & set(clean_dict_metal) & set(clean_dict_hard) & set(clean_dict_rough))
all_ids_intersection
len(all_ids_intersection)

2550

In [142]:
#creating matrix X
X = []

for fs_id in all_ids_intersection:
    feature_vector = [dict_bright[fs_id], dict_metal[fs_id], dict_hard[fs_id],dict_rough[fs_id]]
    X.append(feature_vector)
len(feature_vector)    
X = np.array(X)    
#X  #printing out matrix 

array([[  4.94935029e+01,   3.03423434e-01,   8.60129777e+01,
          1.34663809e+01],
       [  4.96059763e+01,   4.96132909e-01,   5.98434937e+01,
          2.78915201e-01],
       [  5.99234549e+01,   4.47256703e-01,   9.69855346e+01,
          1.12387737e+01],
       [  5.18306509e+01,   4.05871622e-01,   7.65996738e+01,
          4.15014651e+00],
       [  6.58465332e+01,   4.98488500e-01,   8.81398878e+01,
          1.39395031e-01],
       [  5.31394332e+01,   3.91433161e-01,   3.65094308e+01,
          2.25034395e+00],
       [  8.31892166e+01,   7.49176627e-01,   9.87854159e+01,
          4.75837064e+02],
       [  7.00812579e+01,   3.50924235e-01,   6.24631734e+01,
          6.32816261e-01],
       [  6.77407999e+01,   5.54721578e-01,   3.08313996e+01,
          1.62456057e+01],
       [  8.25793382e+01,   5.72324356e-01,   6.88402647e+01,
          5.63975663e+01],
       [  6.96856491e+01,   5.52012823e-01,   4.56248223e+01,
          2.48952441e+01],
       [  5.86699623e

In [143]:
len(X)

2550

In [144]:
X.shape

(2550, 4)

In [145]:
#confirming it matches in size as supposed to. ID DOES NOT BECAUSE OF THE NAN ISSUE.NEED TO BE DONE BEFORE
print len(all_ids_intersection)

2550


all_ids = list_bright_analysis + list_metal_analysis + list_bright_analysis + list_rough_analysis
len (all_ids)

In [157]:
y = []
NB_SOUNDS = len(X)  #here will get same result if using "all_ids_intersection" instead of "X"
NB_LABELS = len(feature_vector)

y = np.zeros((NB_SOUNDS, NB_LABELS), dtype=int)

for idx, sound_id in enumerate(all_ids_intersection): # recorro todos los sonidos (lineas)
    if sound_id in bright_list: # si el sonido es bright
        y[idx][0] = 1 # add a 1 for each line (soundid) "idx" and the columns (label) 0....
    if sound_id in metallic_list: 
        y[idx][1] = 1 # add a 1 for each line (soundid) "idx" and the columns (label) 1....
    if sound_id in hard_list: 
        y[idx][2] = 1 # add a 1 for each line (soundid) "idx" and the columns (label) 2....
    if sound_id in rough_list: 
        y[idx][3] = 1 # add a 1 for each line (soundid) "idx" and the columns (label) 3....´

        
#Y = np.array(y)    

In [147]:
y.shape

(2550, 4)

In [148]:
#y  #printing out y matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1,

In [149]:
#SPLIT
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)


In [150]:
X_train.shape, y_train.shape
X_test.shape, y_test.shape

((510, 4), (510, 4))

In [151]:
#X_train  #cheking X_train matrix values

In [152]:
#checking it there are nan values
#print(np.isinf(X))


In [153]:
#print(np.isnan(X))

In [154]:
#print(np.isinf(y))

In [155]:
#print(np.isnan(y))

In [156]:
#TRAIN
clf = OneVsRestClassifier(SVC(kernel='linear'))
clf.fit(X, y)

OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
          n_jobs=1)

#will need to check later on for optimization purposes
from sklearn.model_selection import GridSearchCV
from sklearn import svm

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svr = svm.SVC()

clf = GridSearchCV(svr,parameters)
clf.fit(X,y)

In [158]:
#clf.predict_proba(X)

In [159]:
clf.score(X, y, sample_weight=None)

0.30549019607843136

In [160]:
#clf.predict(X_test)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0,

#example different for precision_recall
from sklearn.metrics import precision_recall_fscore_support as score

predicted = [1,2,3,4,5,1,2,1,1,4,5] 
y_test = [1,2,3,4,5,1,2,1,1,4,1]

precision, recall, fscore, support = score(y_test, predicted)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

In [161]:
#The recall is the ratio tp / (tp + fn) 
#where tp is the number of true positives and fn the number of false negatives.
#The recall is intuitively the ability of the classifier to find all the positive samples.
y_true = y_test
y_pred = clf.predict(X_test)
 
x1 = recall_score(y_true, y_pred, average='micro') 
x2 = recall_score(y_true, y_pred, average='macro') 
x3 = recall_score(y_true, y_pred, average='weighted')
x1,x2,x3

(0.0053475935828877002, 0.0052100118165216459, 0.0053475935828877002)

In [162]:
#The precision is the ratio tp / (tp + fp) 
#where tp is the number of true positives and fp the number of false positives. 
#The precision is intuitively the ability of the classifier not to label as positive a sample that is negative.

#from sklearn.metrics import precision_score

macro_prec=precision_score(y_true, y_pred, average='macro') 
weigh_prec= precision_score(y_true, y_pred, average='weighted')
micro_prec=precision_score(y_true, y_pred, average='micro')

micro_prec, macro_prec, weigh_prec 


(1.0, 0.5, 0.51871657754010692)

In [163]:
#ACCURACY

y_true = X_train.shape
y_pred = X_test.shape
accuracy_score(y_true, y_pred)


0.5

In [164]:
#TEST....classification report
#NEED TO CHECK PRECISION AND RECALL...RESULTS SEEM INCORRECT! (all 100%) NEED TO FIND OUT WHAT IS GOING ON!

#from sklearn.metrics import classification_report
#y_test = clf.predict(y_test) takes it from above
y_pred = clf.predict(X_test)
categories = ['bright', 'metal', 'hard', 'rough']
print(classification_report(y_test, y_pred, target_names=categories))

             precision    recall  f1-score   support

     bright       1.00      0.01      0.02        87
      metal       1.00      0.01      0.02       107
       hard       0.00      0.00      0.00        85
      rough       0.00      0.00      0.00        95

avg / total       0.52      0.01      0.01       374



In [165]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      0.01      0.02        87
          1       1.00      0.01      0.02       107
          2       0.00      0.00      0.00        85
          3       0.00      0.00      0.00        95

avg / total       0.52      0.01      0.01       374



#PEARSON CORRELATIONS
#intersection nb_sounds and surrey analisis
intersection_nb_surrey = list(set(nb_sounds)&set(all_ids_intersection))
import scipy from scipy.stats import pearsonr
x = scipy.array([-0.65499887, 2.34644428, 3.0]) y = scipy.array([-1.46049758, 3.86537321, 21.0])
r_row, p_value = pearsonr(x, y)

r_row, p_value
